version: '3'
services:
  psql:
    container_name: db_dev
    image: postgres
    environment:
      - POSTGRES_DB=${PSQL_NAME}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
  redis:
    image: redis:latest
  api-dev:
    container_name: api_dev
    build: ./backend
    env_file: .env.dev
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - psql
    expose:  # new
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`271b83d7f474.vps.myjino.ru`)"
  celery:
    container_name: celery_dev
    build: ./backend
    command: celery -A project worker --loglevel=info --beat
    volumes:
      - ./backend:/backend
    depends_on:
      - psql
      - redis
  app:
    container_name: react_app_dev
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/frontend/src
    expose:  # new
      - 3000
    command: >
      sh -c "npm start"
    env_file:
      - .env.dev
  traefik:
    container_name: traefik
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    volumes:
    
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  traefik-public-certificates:
# docker-compose up --scale celery=3

# /walletwatch/dev/app/
