version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  psql:
    container_name: db_dev
    image: postgres
    environment:
      - POSTGRES_DB=${PSQL_NAME}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
  redis:
    image: redis:latest
    container_name: wallet_watch_app-redis
  celery:
    container_name: celery_dev
    build: ./backend
    command: celery -A project worker --loglevel=info --beat
    volumes:
      - ./backend:/backend
    depends_on:
      - psql
      - redis
      - django
    environment:
      - REDIS_HOST=wallet_watch_app-redis
  django:
    build: ./backend
    env_file: .env.dev
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 project.asgi:application"
    depends_on:
      - traefik
      - psql 
      - redis
    environment:
      - REDIS_HOST=wallet_watch_app-redis  # Указываем имя контейнера Redis
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`dev.c0d2aa9fd631.vps.myjino.ru`) && PathPrefix(`/walletwatch/api/`)" # Ваш домен
      - "traefik.http.services.django.loadbalancer.server.port=8000"
  react:
    build: ./frontend
    env_file: .env.dev
    command: sh -c "npm start"
    depends_on:
      - traefik
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`dev.c0d2aa9fd631.vps.myjino.ru`)" # Ваш домен
      - "traefik.http.services.react.loadbalancer.server.port=3000"

networks:
  web:
    external: true
