version: '3.8'

services:
  traefik_dev:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  psql_dev:
    container_name: psql_dev
    image: postgres
    environment:
      - POSTGRES_DB=${PSQL_NAME}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
  redis_dev:
    image: redis:latest
    container_name: wallet_watch_app_redis_dev
  celery_dev:
    container_name: celery_dev
    build: ./backend
    command: celery -A project worker --loglevel=info --beat
    volumes:
      - ./backend:/backend
    depends_on:
      - psql_dev
      - redis_dev
      - django_dev
    expose:
      - "8001"
    environment:
      - REDIS_HOST=wallet_watch_app-redis
  django_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env.dev
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py clear_cache && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 project.asgi:application"
    depends_on:
      - traefik_dev
      - psql_dev
      - redis_dev
    environment:
      - REDIS_HOST=wallet_watch_app-redis  # Указываем имя контейнера Redis
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django_dev.rule=Host(`dev.c0d2aa9fd631.vps.myjino.ru` ) || Host(`dev.gryumova.ru`) && PathPrefix(`/api`)" # Ваш домен
      - "traefik.http.routers.django_dev.priority=2"
      - "traefik.http.services.django_dev.loadbalancer.server.port=8000"
      # Маршрут для WebSocket
      - "traefik.http.routers.django_dev-ws.rule=Host(`dev.c0d2aa9fd631.vps.myjino.ru`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.django_dev-ws.priority=3"
      - "traefik.http.services.django_dev.loadbalancer.server.port=8000"
  react_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env.dev 
    volumes:
      - ./frontend/src:/frontend/src
    command: sh -c "npm start"
    depends_on:
      - traefik_dev
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react_dev.rule=Host(`dev.c0d2aa9fd631.vps.myjino.ru`) || Host(`dev.gryumova.ru`)" # Ваш домен
      - "traefik.http.routers.react_dev.priority=1"
      - "traefik.http.services.react_dev.loadbalancer.server.port=3000"

networks:
  web:
    external: true
