version: '3.8'

services:
  psql:
    image: postgres
    container_name: psql
  redis:
    image: redis:latest
    container_name: wallet_watch_app-redis-prod
  celery:
    build: ./backend
    command: celery -A project worker --loglevel=info --beat
    volumes:
      - ./backend:/backend
    depends_on:
      - psql
      - redis
      - django
    expose:
      - "8001"
    environment:
      - REDIS_HOST=wallet_watch_app-redis-prod
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py clear_cache && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 project.asgi:application"
    depends_on:
      - psql 
      - redis
    networks:
      - web
      - default
    expose:
      - "8000"
  react_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - web
    command: sh -c "npm start"
    expose:
      - "3000"

networks:
  web:
    external: true
  default:
    internal: true
