[entryPoints]
  [entryPoints.web-secure]
    address = ":443"

[api]
  insecure = false
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "e.gryumova@gmail.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web-secure"
