# Настройка точек входа
[entryPoints]
  [entryPoints.web]
    address = ":80"

# Конфигурация маршрутов HTTP
[http]

  # Настройка провайдеров
  [http.routers]
    [http.routers.api-dev]
      rule = "Host(`gryumova.ru`) || Host(`gryumova.ru`)"
      service = "api-dev"
      entryPoints = ["web"]

  # Настройка сервисов
  [http.services]
    [http.services.api-dev.loadBalancer]
      [[http.services.api-dev.loadBalancer.servers]]
        url = "http://localhost:8000"

# Конфигурация провайдеров
[providers]
  [providers.docker]
    exposedByDefault = false

# Настройка логирования
[log]
  level = "DEBUG"
