# Generated by Django 5.0.2 on 2024-02-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='asset_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
