# Generated by Django 5.0.2 on 2024-02-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_balance_asset_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
