# Generated by Django 4.2.10 on 2024-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=20)),
                ('network_url', models.CharField(max_length=256)),
                ('network_abi', models.TextField(default='')),
                ('network_chain', models.TextField(default=0))
            ],
        ),
    ]
