# Generated by Django 4.2.10 on 2024-02-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='network',
        ),
        migrations.AddField(
            model_name='balance',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.network'),
        ),
    ]
