# Generated by Django 5.0.3 on 2024-04-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20240321_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_abi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_chain',
            field=models.CharField(default=''),
        ),
    ]
