# Generated by Django 5.0.3 on 2024-04-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_network_network_abi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='network',
        ),
        migrations.AddField(
            model_name='asset',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.network'),
        ),
    ]
