# Generated by Django 5.0.3 on 2024-04-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_asset_network_asset_network_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='delta',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='asset',
            name='track',
            field=models.BooleanField(default=False),
        ),
    ]
