version: '3.8'

services:
  traefik_dev:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    network:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  web:
    external: true