version: '3.8'

services:
  traefik_dev:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  react_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env.dev 
    command: sh -c "npm start"
    depends_on:
      - traefik_dev
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react_dev.rule=Host(`dev.c0d2aa9fd631.vps.myjino.ru`) || Host(`dev.gryumova.ru`)" # Ваш домен
      - "traefik.http.services.react_dev.loadbalancer.server.port=3000"

networks:
  web:
    external: true