version: "3"

services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - --api.dashboard=true
      - --log.level=INFO
      #- --log.filepath=/var/log/traefik.log
      - --accesslog=true
      #- --accesslog.filepath=/var/log/traefik-access.log
      - --providers.docker.network=proxy
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      # remove next line when using Traefik v2
      - --entrypoints.websecure.asDefault=true 
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --certificatesresolvers.myresolver.acme.email=e.gryumova@gmail.com
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`traefik.c0d2aa9fd631.vps.myjino.ru`)
      - traefik.http.routers.mydashboard.service=api@internal
    ports:
      - 443:443
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - default
    restart: always

networks:
  default:
    external:
      name: gateway

volumes:
  letsencrypt:

# docker network create traefik_webgateway

# docker network create \
#   --driver=bridge \
#   --attachable \
#   --internal=false \
#   gateway