version: "3"

services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.dashboard=true"
      - "--log.level=INFO"
      #- --log.filepath=/var/log/traefik.log
      - "--accesslog=true"
      #- --accesslog.filepath=/var/log/traefik-access.log
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`c0d2aa9fd631.vps.myjino.ru`)
      - traefik.http.routers.mydashboard.service=api@internal
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - default
    restart: always

networks:
  default:
    external:
      name: gateway

volumes:
  letsencrypt:

# docker network create traefik_webgateway

# docker network create \
#   --driver=bridge \
#   --attachable \
#   --internal=false \
#   gateway