version: '3.8'

services:
  traefik_dev:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  psql:
    image: postgres
    container_name: psql
    environment:
      - POSTGRES_DB=${PSQL_NAME}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
  redis:
    image: redis:latest
    container_name: wallet_watch_app-redis
  celery:
    build: ../backend
    command: celery -A project worker --loglevel=info --beat
    volumes:
      - ../backend:/backend
    depends_on:
      - psql
      - redis
      - django
    expose:
      - "8001"
    environment:
      - REDIS_HOST=wallet_watch_app-redis
  django:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/backend
    command: bash -c "python manage.py clear_cache && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 project.asgi:application"
    depends_on:
      - psql 
      - redis
    networks:
      - web
      - default
    environment:
      - REDIS_HOST=wallet_watch_app-redis 
      - PSQL_NAME=${PSQL_NAME}
      - PSQL_USER=${PSQL_USER}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_HOST=psql
      - PSQL_PORT=${PSQL_PORT}
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`dev.c0d2aa9fd631.vps.myjino.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.django.priority=100"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
  react_dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://dev.c0d2aa9fd631.vps.myjino.ru
    command: sh -c "npm start"
    depends_on:
      - traefik_dev
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react_dev.rule=Host(`dev.c0d2aa9fd631.vps.myjino.ru`)"
      - "traefik.http.routers.react_dev.priority=50"
      - "traefik.http.services.react_dev.loadbalancer.server.port=3000"

networks:
  web:
    external: true
