name: Django CI

on:
  push:
    branches: [ "make_ci" ]
  pull_request:
    branches: [ "make_ci" ]

jobs:
  backend-tests:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 2608
          POSTGRES_DB: wallet

        ports:
          - 5432:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      run: |
        pip install coverage
        cd backend && coverage run --source='.' --omit='/usr/lib/python3/dist-packages/*' manage.py test && coverage report --fail-under=75 && coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: WalletWatch/wallet_watch_app   

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Frontend Dependencies
        run: |
          cd frontend && npm install

      - name: Run Frontend Tests
        run: |
          cd frontend && npm test -- --coverage

      - name: Upload Frontend coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
