name: Deploy

on:
  push:
    branches:
      - main
      - develop
      - traefik
      
jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Stop and remove containers, networks
        if: github.ref == 'refs/heads/main'
        run: |
          docker-compose --env-file .env.prod -f /root/actions-runner/_work/wallet_watch_app/wallet_watch_app/docker-compose.prod.yml down
      - name: Remove unused data
        if: github.ref == 'refs/heads/docker'
        run: |
          docker-compose --env-file .env.dev -f /root/actions-runner/_work/wallet_watch_app/wallet_watch_app/docker-compose.dev.yml down

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
    
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        docker-compose --env-file .env.prod -f /root/actions-runner/_work/wallet_watch_app/wallet_watch_app/docker-compose.prod.yml up -d

    - name: Deploy to development
      if: github.ref == 'refs/heads/docker'
      run: |
        docker-compose --env-file .env.dev -f /root/actions-runner/_work/wallet_watch_app/wallet_watch_app/docker-compose.dev.yml up -d
