# name: Deploy

# # Trigger the workflow on push and
# # pull request events on the master branch
# on:
#   push:
#     branches: ["master"]
#   pull_request:
#     branches: ["master"]

# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#     - name: Update code
#       run:
#         cd /root/wallet_watch_app/frontend && git pull origin master;
#     - name: Deploy Django to server
#       run:
#         source /root/wallet_watch_app/env/bin/activate;
#         cd /root/wallet_watch_app && make deploy;
#         deactivate
#     - name: Deploy React to server
#       run:
#         cd /root/wallet_watch_app/client && npm install && npm run build;
#         rm -r /var/www/3f9215732d0c.vps.myjino.ru;
#         mkdir /var/www/3f9215732d0c.vps.myjino.ru;
#         cp -r /root/wallet_watch_app/client/build/* /var/www/3f9215732d0c.vps.myjino.ru;
#         sudo systemctl restart nginx;
