name: Deploy

on:
  push:
    branches:
      - main
      - develop
      - docker

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        docker stop $(docker ps -a -q)
        docker rm $(docker ps -a -q)
        docker-compose --env-file .env.prod -f docker-compose.prod.yml up -d

    - name: Deploy to development
      if: github.ref == 'refs/heads/docker'
      run: |
        if docker ps | grep -q -v CONTAINER; then
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
        fi
        docker-compose --env-file .env.dev -f /root/actions-runner/_work/wallet_watch_app/wallet_watch_app/docker-compose.dev.yml up -d
