name: Deploy

on:
  push:
    branches:
      - main
      - docker
      - traefik

jobs:
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run traefik 
      run: |
        docker network create traefik_webgateway
        cd traefik && docker-compose docker-compose.yml up -d
