name: Traefik

on:
  push:
    branches:
      - main
      - docker

jobs:
  traefik:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run traefik 
        run: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker network rm web
          docker network create --driver=bridge --attachable --internal=false web
          cd traefik && docker-compose -f docker-compose.yml up -d
