name: Traefik

on:
  push:
    branches:
      - main
      - docker

jobs:
  traefik:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run traefik 
        run: |
          docker network create traefik_webgateway
          cd traefik && docker-compose -f docker-compose.yml up -d
