name: Traefik

on:
  push:
    branches:
      - main
      - docker
      - traefik

jobs:
  traefik:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run traefik 
        run: |
          docker network create --driver=bridge --attachable --internal=false web
          cd traefik && docker-compose -f docker-compose.yml up -d
          docker-compose -f /root/actions-runner/_work/wallet_watch_app/wallet_watch_app/docker-compose.yml up -d 
